### ISSUE TITLE
Last css declaration in block does not end in ";"

### ISSUE THREAD

**Issue by dyspop** [centralcollegenottingham/HTML-Email-Boilerplate-Redux#14]
I'm thinking this is probably more likely a gulp issue, but calling it out here first in case the author(s) know something I don't

examples:

```
a[x-apple-data-detectors]{color:inherit!important;text-decoration:none!important;font-size:inherit!important;font-family:inherit!important;font-weight:inherit!important;line-height:inherit!important}
```

```
table#gmailapp-android-fix{display:none}
```

**Comment by dyspop** [comment]
but the actual declarations contain the `;` 
https://github.com/centralcollegenottingham/HTML-Email-Boilerplate-Redux/search?utf8=%E2%9C%93&q=table%23gmailapp-android-fix

**Comment by jamesmacwhite** [comment]
Hi.

Its part of the minifying process when running `gulp`. Basically in order to save on file size, safe CSS optimisations are being run on the boilerplate. As far as I know, this shouldn't cause any issues with email clients, as its it is valid CSS for the last inline rule to not be ended with a semi colon, it also only happens on the last CSS inline rule.

If however there is a specific usage case where this causes issues, I'll investigate further.

**Comment by dyspop** [comment]
is there an option to disable?

**Comment by jamesmacwhite** [comment]
Not currently. The behaviour is coming from:

https://github.com/jakubpawlowicz/clean-css

There are various configuration options that can be applied in the gulpfile, I can see if there is a specific parameter that controls it from the docs and potentially work it as a user controlled configuration option, but it might not be an explicit option in clean-css, just a optimisation part of a general parameter.

**Comment by jamesmacwhite** [comment]
As discussed, I'll close this issue for now, if however clean-css choose to implement this as a boolean setting, I'll happily implement into our project as a user controllable option.
